name: PMD Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd-analysis:
    name: PMD Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'java-basic'
          analyzeModifiedFilesOnly: false
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif
            
      - name: Upload PMD Report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: app/build/reports/code-analysis
