name: PMD Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd-code-scan:
    name: PMD Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'java-basic'
          analyzeModifiedFilesOnly: false
          
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations > 2
        run: exit 1
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif
