name: PMD Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd-analysis:
    name: PMD Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Run PMD Code Analysis
        uses: amar-learning/pmd-code-analysis@v1
        with:
          java-version: '21'
          pmd-version: '6.36.0'
          source-folder: 'src'
          report-format: 'html'
          report-output-folder: 'pmd-report'

      - name: Upload PMD Report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: app/build/reports/code-analysis
